services:
  marketplace-profile-api:
    build:
      dockerfile: ./Dockerfile
      context: ./
    restart: always
    image: marketplace-profile-api
    container_name: marketplace-profile-api
    volumes:
      - /home/kinoko/logs/marketplace-profile-api:/logs
    #      - ./logs:/logs                             # Для отладки на windows машине
    networks:
      - backend
    ports:
      - "33302:33302"

networks:
  backend:
    external: true
