logging:
  config: 'classpath:log4j2.yml'
  level:
    com.netflix.discovery.shared: error

spring:
  application:
    name: marketplace-profile-api
  servlet:
    multipart:
      max-file-size: 5MB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://kinoko.su:5432/mp_db_dev
    username: mp_dev_user
    password: mp_dev_passwd

app:
  minio:
    login: kinadmin
    password: Kinok0Jap17096065
    bucket: mp-avatars
    urls:
      api: http://minio:9000
      public: https://bobr.kinoko.su/api/v1/buckets/mp-avatars/objects/download?prefix=

springdoc:
  api-docs:
    enabled: true
    path: /api/profile/docs
  swagger-ui:
    csrf:
      enabled: true
    path: /api/profile/swagger

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://marketplace-eureka:33307/eureka

server:
  port: 33302
