name: Маркетплейс услуг

on:
  push: {}            # Запуск на каждый коммит во всех ветках

env:
  JAVA_VERSION: '21'
  TARGET_DIR: /home/kinoko/marketplace/marketplace-profile-api
  BACKUP_DIR: /home/kinoko/backup/marketplace-profile-api
  JAR_DIR: /tmp/marketplace/marketplace-profile-api

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Upload artifacts
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v5
        with:
          name: app-jars
          path: '**/build/libs/*.jar'

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Download built JARs
        uses: actions/download-artifact@v6
        with:
          name: app-jars
          path: ${{ env.JAR_DIR }}

      - name: Stop and remove existing containers
        run: |
          if [ -f "${{ env.TARGET_DIR }}/docker-compose.yml" ]; then
            docker compose -f "${{ env.TARGET_DIR }}/docker-compose.yml" down
          fi

      - name: Clean target directory
        run: sudo rm -rf ${{ env.TARGET_DIR }} && sudo mkdir -p ${{ env.TARGET_DIR }}

      - name: Copy project files
        run: |
          sudo cp -r ./* ${{ env.TARGET_DIR }}
          sudo chown -R kinoko:kinoko ${{ env.TARGET_DIR }}

      - name: Copy JAR to server
        run: |
          sudo cp -r ${{ env.JAR_DIR }}/* ${{ env.TARGET_DIR }}
          sudo rm -r ${{ env.JAR_DIR }}

      - name: Build and deploy with Docker Compose
        run: |
          if [ -f "${{ env.TARGET_DIR }}/docker-compose.yml" ]; then
            docker compose -f ${{ env.TARGET_DIR }}/docker-compose.yml rm -f
          fi
          docker compose -f ${{ env.TARGET_DIR }}/docker-compose.yml up --build -d
          sleep 60
          if docker compose -f ${{ env.TARGET_DIR }}/docker-compose.yml logs | grep -i "\[ERROR\]"; then
            echo "Ошибка деплоя. В логах найдены ошибки"
            docker compose -f ${{ env.TARGET_DIR }}/docker-compose.yml logs | grep -i "\[ERROR\]";
            exit 1
          else
            echo "Ошибок в логах не найдено. Деплой успешен"
          fi

      - name: Confirm deployment
        run: |
          sudo rm -rf ${{ env.BACKUP_DIR }}
          echo "Деплой окончен"
